# -- Language Configuration --
# For more details: https://blowfish.page/docs/configuration/#language-and-i18n

label = "English"
direction = "ltr"
weight = 1
contentDir = "content/en"
title = "Manuel Anrig"
copyright = "© 2026 — Manuel Anrig"

[params]
  displayName = "EN"
  isoCode = "en"
