# -- Main menu --
# For more details: https://blowfish.page/docs/configuration/#main-menu

[[main]]
  identifier = "blog"
  name = "Blog"
  url = "/blog/"
  weight = 10

[[main]]
  identifier = "racing"
  name = "Racing"
  url = "/racing/"
  weight = 20

[[main]]
  identifier = "resume"
  name = "Resume"
  url = "/resume/"
  weight = 30

